### ISSUE TITLE
HFilter usage

### ISSUE THREAD

**Issue by vojtechmusilek** [Strukton-Worksphere/haystack-csharp#71]
Hi, i am using HFilter to parse filter string, and i want to access parsed parts of filter.

Example: 
HFilter.make("building==\"office\" and room==\"ab1\"")
This will create object HFilter.And with
m_a: HFilter.Eq
m_b: HFilter.Eq
and each containing
m_path, m_val

Those values are 'protected' and cannot be accessed, is there any way i can access them?

**Comment by Breederveld** [comment]
Hi, you could always use reflection, but I have made a minor change #73 to the library to expose them as "A" and "B". Available in NuGet library [1.8.3](https://www.nuget.org/packages/ProjectHaystack.Client/1.8.3)
