### ISSUE TITLE
license type?

### ISSUE THREAD

**Issue by epaulson** [Strukton-Worksphere/haystack-csharp#87]
Hello - 

There isn't a license file in this repository. Could you clarify if this code is being made available under any specific license?

**Comment by Breederveld** [comment]
About the question by @tblong the .NET version was mostly updated to gain access to the new language features and some performance gains. However as these aren't used very much right now it seems fair to keep backward-compatibility by multi-targeting netstandard2.0, netstandard2.1, net5.0 and net6.0. I've created #89 for this.
